name: csv_app
description: A Flutter app to load and parse CSV from assets.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: any
  split_view: any

flutter:
  uses-material-design: true
  assets:
    - assets/mydata.csv
